#!/bin/sh

# chkconfig: 345 94 15

# Source function library
. /etc/rc.d/init.d/functions

GLITE_LOCATION=${GLITE_LOCATION:-/opt/glite}
GLITE_LOCATION_VAR=${GLITE_LOCATION_VAR:-${GLITE_LOCATION}/var}

GLITE_CE_PARSER_MASTER=${GLITE_LOCATION}/bin/blparser_master
case "$1" in

  start)
             echo -n "Starting `basename $GLITE_CE_PARSER_MASTER`: " 
             daemon $GLITE_CE_PARSER_MASTER
             RETVAL=$?
             echo 
             ;;

  stop)
             echo -n "Shutting down `basename ${GLITE_CE_PARSER_MASTER}`: "
             killproc ${GLITE_CE_PARSER_MASTER}
             RETVAL=$?
             echo
             ;;

  status)
             status ${GLITE_CE_PARSER_MASTER}
             ;;

  restart)
             $0 stop
	     sleep 4
             $0 start
             ;;

  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
