#!/bin/sh

# chkconfig: 345 94 15

# Source function library
. /etc/rc.d/init.d/functions

GLITE_LOCATION=${GLITE_LOCATION:-/opt/glite}
GLITE_LOCATION_VAR=${GLITE_LOCATION_VAR:-${GLITE_LOCATION}/var}

GLITE_CE_BUPDATERCONDOR=${GLITE_LOCATION}/bin/BUpdaterCondor
GLITE_CE_BNOTIFIERCONDOR=${GLITE_LOCATION}/bin/BNotifierCondor

pidupdfile=$GLITE_LOCATION_VAR/glite-bupdatercondor.pid
pidnotfile=$GLITE_LOCATION_VAR/glite-bnotifiercondor.pid


start()
{

   $GLITE_CE_BUPDATERCONDOR
   echo -n $"Starting ${GLITE_CE_BUPDATERCONDOR}:"
   [ "$?" -eq 0 ] && success || failure 
   echo
   
   $GLITE_CE_BNOTIFIERCONDOR
   echo -n $"Starting ${GLITE_CE_BNOTIFIERCONDOR}:"
   [ "$?" -eq 0 ] && success || failure 
   echo
	      
   echo `pidofproc ${GLITE_CE_BUPDATERCONDOR}` > $pidupdfile 
   echo `pidofproc ${GLITE_CE_BNOTIFIERCONDOR}` > $pidnotfile 
 
}

stop()
{
  if [ -f $pidupdfile ]; then
    pid=`cat $pidupdfile`
    if [ ! -z "$pid" ]; then
       kill $pid
       echo -n $"Stopping ${GLITE_CE_BUPDATERCONDOR}:"
       [ "$?" -eq 0 ] && success || failure 
       echo
    fi
    rm -f $pidupdfile
  else
    echo $pidupdfile does not exist - ${GLITE_CE_BUPDATERCONDOR} not running? >&2
  fi

  if [ -f $pidnotfile ]; then
    pid=`cat $pidnotfile`
    if [ ! -z "$pid" ]; then
       kill $pid
       echo -n $"Stopping ${GLITE_CE_BNOTIFIERCONDOR}:"
       [ "$?" -eq 0 ] && success || failure         
       echo
    fi
    rm -f $pidnotfile
  else
    echo $pidnotfile does not exist - ${GLITE_CE_BNOTIFIERCONDOR} not running? >&2
  fi

}

status()
{
  if [ -f $pidupdfile ]; then
     pid=`cat $pidupdfile`
        if [ ! -z "$pid" ]; then
           if ps p $pid >/dev/null 2>&1; then
              echo ${GLITE_CE_BUPDATERCONDOR} running as $pid 
              continue
           fi
        fi
  else
  	echo ${GLITE_CE_BUPDATERCONDOR} not running
  fi

  if [ -f $pidnotfile ]; then
     pid=`cat $pidnotfile`
        if [ ! -z "$pid" ]; then
           if ps p $pid >/dev/null 2>&1; then
              echo ${GLITE_CE_BNOTIFIERCONDOR} running as $pid 
              continue
           fi
        fi
  else
  	echo ${GLITE_CE_BNOTIFIERCONDOR} not running
  fi

}

case x$1 in
	xstart)	start;;
	xstop)	stop;;
	xrestart) stop; start;;
	xstatus) status;;
	x*)	echo usage: $0 start,stop,restart,status >&2
		exit 1;;
esac


