#!/bin/sh

# Source function library
. /etc/rc.d/init.d/functions

GLITE_LOCATION=${GLITE_LOCATION:-/opt/glite}
GLITE_LOCATION_VAR=${GLITE_LOCATION_VAR:-${GLITE_LOCATION}/var}

[ -f /etc/glite.conf ] && . /etc/glite.conf

[ -f $HOME/.glite.conf ] && . $HOME/.glite.conf

[ -n "$GLITE_CE_BAPARSER_PIDFILE" ] && pidfile=$GLITE_CE_BAPARSER_PIDFILE ||
	pidfile=$GLITE_LOCATION_VAR/glite-baparser.pid

GLITE_CE_BAPARSER=${GLITE_LOCATION}/bin/BAParser
GLITE_CE_BAPARSER_FLAG="-D"

start()
{
	$GLITE_CE_BAPARSER $GLITE_CE_BAPARSER_FLAG
        [ "$?" -eq 0 ] && success $"startup" || failure $" startup" 
        
	echo

	echo `pidofproc ${GLITE_CE_BAPARSER}` > $pidfile 
}

stop()
{
	if [ -f $pidfile ]; then
		pid=`cat $pidfile`
		kill $pid
		[ "$?" -eq 0 ] && success $"${GLITE_CE_BAPARSER} shutdown" || failure $"${GLITE_CE_BAPARSER} shutdown" 
                echo ""
		rm -f $pidfile
	else
		echo $pidfile does not exist - ${GLITE_CE_BAPARSER} not running? >&2
		return 1
	fi
}

status()
{
	if [ -f $pidfile ]; then
		pid=`cat $pidfile`
		if ps p $pid >/dev/null 2>&1; then
			echo ${GLITE_CE_BAPARSER} running as $pid 
			return 0
		fi
	fi

	echo ${GLITE_CE_BAPARSER} not running
	return 1
}

case x$1 in
	xstart)	start;;
	xstop)	stop;;
	xrestart) stop; start;;
	xstatus) status;;
	x*)	echo usage: $0 start,stop,restart,status >&2
		exit 1;;
esac
