#!/bin/sh

# chkconfig: 345 94 15

# Source function library
. /etc/rc.d/init.d/functions

GLITE_LOCATION=${GLITE_LOCATION:-/opt/glite}
GLITE_LOCATION_VAR=${GLITE_LOCATION_VAR:-${GLITE_LOCATION}/var}

[ -f $GLITE_LOCATION/etc/blah.config ] && . $GLITE_LOCATION/etc/blah.config

GLITE_CE_BUPDATER=$bnotifier_path
GLITE_CE_BNOTIFIER=$bupdater_path

case "$1" in

  start)
	      echo -n "Starting `basename $GLITE_CE_BUPDATER`: " 
	      daemon --user=tomcat $GLITE_CE_BUPDATER
              RETVAL=$?
	      echo 

              echo -n "Starting `basename $GLITE_CE_BNOTIFIER`: " 
              daemon --user=tomcat $GLITE_CE_BNOTIFIER
              RETVAL=$?
              echo
              ;;

  stop)
       	      echo -n "Shutting down `basename ${GLITE_CE_BUPDATER}`: "
       	      killproc ${GLITE_CE_BUPDATER} 
              RETVAL=$?
       	      echo

	      echo -n "Shutting down `basename ${GLITE_CE_BNOTIFIER}`: "
              killproc ${GLITE_CE_BNOTIFIER} 
              RETVAL=$?
              echo
              ;;

  status)
	     status ${GLITE_CE_BUPDATER}
	     status ${GLITE_CE_BNOTIFIER}
	     ;;

  restart)
            $0 stop
            $0 start
            ;;

  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0

