#!/bin/sh

#  Copyright (c) Members of the EGEE Collaboration. 2007-2010. 
#
#    See http://www.eu-egee.org/partners/ for details on the copyright
#    holders.  
#  
#    Licensed under the Apache License, Version 2.0 (the "License"); 
#    you may not use this file except in compliance with the License. 
#    You may obtain a copy of the License at 
#  
#        http://www.apache.org/licenses/LICENSE-2.0 
#  
#    Unless required by applicable law or agreed to in writing, software 
#    distributed under the License is distributed on an "AS IS" BASIS, 
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
#    See the License for the specific language governing permissions and 
#    limitations under the License.
#


# chkconfig: 345 94 15

# Source function library
. /etc/rc.d/init.d/functions

GLITE_LOCATION=${GLITE_LOCATION:-/opt/glite}
GLITE_LOCATION_VAR=${GLITE_LOCATION_VAR:-${GLITE_LOCATION}/var}

GLITE_CE_PARSER_MASTER=${GLITE_LOCATION}/bin/blparser_master
case "$1" in

  start)
             echo -n "Starting `basename $GLITE_CE_PARSER_MASTER`: " 
             daemon $GLITE_CE_PARSER_MASTER
             RETVAL=$?
             echo 
             ;;

  stop)
             echo -n "Shutting down `basename ${GLITE_CE_PARSER_MASTER}`: "
             killproc ${GLITE_CE_PARSER_MASTER}
             RETVAL=$?
             echo
             ;;

  status)
             status ${GLITE_CE_PARSER_MASTER}
             ;;

  restart)
             $0 stop
	     sleep 4
             $0 start
             ;;

  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
